### PR TITLE
Project: Using Bootstrap

### PR DESCRIPTION
**Pull request by krys2fa**
Milestones:

-- developed a responsive webpage by using the Bootstrap framework.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @krys2fa  👋

You've done quite well on this.👍

However, there are just a few fixes to be made.
Kindly make the following adjustments:

- [ ] Please adjust the navbar area of your project so it looks like the original webpage. Simply add more left and right margins to the navbar content. Also, increase the size of the `Sign In` and `Subscribe` links on the navbar. In addition, make the 11 navbar links `US`, `World`, `Tech` just below the header look more bolder just as seen in the original webpage.

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200424-191322

**THIS IS YOURS**👇
ice_screenshot_20200424-191313


- [ ] - Also kindly make the navbar fixed to the top, just as seen in the original webpage.

- [ ] In addition to the sections `In the Magazine`, and `Editor's Picks`, the images found in these sections are smaller in dimensions than seen on the original webpage, kindly increase their sizes particularly on a desktop(1400px) screen size.
**THIS IS YOURS**👇
ice_screenshot_20200424-191538

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200424-191512

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by krys2fa** [comment]
Thanks @mikenath223. Requested changes have been effected.

**Review by christianotieno — CHANGES_REQUESTED** [review]
## Awesome work implementing the changes @krys2fa

### [The clone](https://raw.githack.com/krys2fa/newsweek-clone/newsweek-home/index.html) shows good use bootstrap. :100: 

- A few required changes: I used a (1920 x 1080) screen display resolution when performing this review. Kindly note that for this project, we have to make sure nothing is messed up. Please see the difference in the source page and the clone below: 

| [Current clone](https://raw.githack.com/krys2fa/newsweek-clone/newsweek-home/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
| clone-styling | newsweek|


- I'd suggest that you be mindful of how you are centring the entire content of the page. 
- Update the README file and add make sure the screenshot of the clone is showing.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Christian Otieno](https://github.com/christianotieno)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Comment by krys2fa** [comment]
Thanks for the review @christianotieno. I have made the requested changes.

**Comment by christianotieno** [comment]
Kindly submit another review.

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED 
This project has been approved as the main objectives and requirements have been met. Below are my optional suggestions we can carry on on this project to make it look like the source page.
##

- I'd advise we try and ensure we have paid more attention to detail.
- We can always improve on some areas of the cloned page. 
1. Like adding gutters to the sections as present in the source page. 
2. Making sure the width and height of each section match the ones on the source page and making sure nothing looks odd.
##
- Good luck with your next tasks @krys2fa. You are free to merge to master.

Cheers
[Christian Otieno](https://github.com/christianotieno)

**Comment by krys2fa** [comment]
Thanks for the review and approval @christianotieno 👍.
I will merge and later implement the changes to improve the project.

**Pull request merged**
